### PR TITLE
Create tags test. test for create single tag and create tag in category

### PR DESCRIPTION
**Pull request by cisko3000**
As much as I could do today.

### CODE REVIEW

**Comment by paris3200** [comment]
It looks like you missed the '()' on the print statement.  Are you using python 2?

**Comment by cisko3000** [comment]
Oh shoot, yeah I think I am

Francisco Bárcena
Web Developer
www.LosAngelesCoder.com

**Comment by paris3200** [comment]
It looks like to use print() in version 3.x and 2.x you need to add this:

    from __future__ import print_function

to the top of the file.  Then you can use the Python 3 print() function for both versions.  

If you'll get it passing I will merge it.  Thank you for writing those test.

**Comment by cisko3000** [comment]
Alright, I think I can do that tomorrow. Of the few times I decide to use
print x instead of print(x), it bites me in the butt... Haha

Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by paris3200** [comment]
Looks like there is another python 2 vs python 3 error with one of the test.

**Pull request merged**
