### PR TITLE
Added API for component and vue.js click UI to check-in check-out

### PR DESCRIPTION
**Pull request by cisko3000**
This is just a start, but you can now see a list of components in check-in / check-out, you can click on one and it will populate the transaction form so you can do checkin/checkout. Next I'm gonna add filters like i said in the project planning / features request.

### CODE REVIEW

**Comment by cisko3000** [comment]
Added cool search feature and you can also filter by tags at check-out check-in screen. Also improved unit tests. I think we should create inventory system API at database model class level, then we can create better unit tests because 'create purchase order test' was taking in SKU as form field, but actual form doesn't have SKU it has component pulldown instead.

**Comment by paris3200** [comment]
This commit seems to break transactions and creating purchase orders.  Adding wsgiref to the requirements.txt causes an error.  My understanding is that wsgiref is now part of python 3.6.  I'm ok with dropping support for python 2 if that would make things easier.  

I agree that testing needs some improvement. An API at the database level would really help that. 

 I also think we need to create an outline of how the data flows so we're on the same page.  I'm a little confused on what your plans are for the check-in process.  My thoughts were that components would be added to the purchase order, once components were received the purchase order would be checked and the components checked in.  I'm open to other ideas.

**Comment by cisko3000** [comment]
Yeah I saw that, I don't know what wsgiref is... Maybe it's part of Flask
restful.
  I think you're right, new or existing components can be checked in
through purchase order form. My mistake is that I made a pulldown menu but
it should be input text, and instead have a link/pop up for user to choose
from existing components. I just wanted a way for user to easily order
things that had previously been ordered already.
   My plan for the check in check out is that it is for people to only
check in stuff that is already in system. Kind of like a borrowing system.
They checkout items and then return them. That is my main focus.
  I will put purchase order form and its test back how it was so that its
not broken (with SKU field).

Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by paris3200** [comment]
I checked the requirements for flask-restful and wsgiref isn't listed.  For now, I think we just remove it from the requirements and move on.  

Nice job on the js search.  Do you know how to use js to add form fields on the fly and have them interact with flask?  I would like to be able to add additional line items to Purchase Order by clicking a button.  I haven't been able to figure that out though.  If you could point me in the right direction I would get to working on that.

**Comment by cisko3000** [comment]
Last time I implemented adding lines on the fly, I used jQuery very heavily. This is part of it:
```
		$(".add_row").click(function(event){
			// create the row
			var count = $("#add_row2").attr("the_line");
			var count = parseInt(count) + 1;
			var line_number = $(this).attr("the_line");
			var new_row = $(this).parent().parent().prev().clone();
			//var the_cloned = $(this).parent().children().first();
			var the_cloned = $("select[id*='-employee_id'").first();
			$(the_cloned).select2("destroy");
			var new_painter = $(the_cloned).clone();
			$(the_cloned).select2();
			$(new_painter).attr("id",'schedule_lines-'+count+'-painters-0-employee_id');
			$(new_painter).attr("name",'schedule_lines-'+count+'-painters-0-employee_id');
			$(new_painter).attr("aria-hidden",'');
			$(new_painter).attr("class",'');
			$(new_painter).val('');
			var time_group;
			if ($(this).attr("group") == 1) {
				time_group = 1;
			}
			else {
				time_group = 2;
			}
			$(new_row).html('<td nowrap><button type="button" class="btn btn-default btn-xs del_row"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button> <input id="schedule_lines-'+count+'-gc" name="schedule_lines-'+count+'-gc" value="" type="text">\
			<input id="schedule_lines-'+count+'-time_group" name="schedule_lines-'+count+'-time_group" value="'+time_group+'" type="hidden"></td><td>\
			<input id="schedule_lines-'+count+'-job_number" name="schedule_lines-'+count+'-job_number" value="" type="text"></td>\
			<td><input id="schedule_lines-'+count+'-job_name" name="schedule_lines-'+count+'-job_name" value="" type="text"></td>\
			<td><input id="schedule_lines-'+count+'-address" name="schedule_lines-'+count+'-address" value="" type="text"></td><td>\
				'+$("<div />").append($(new_painter).clone()).html()+'<br>\
					<button class="btn-primary add_painter" the_line="'+count+'" type="button">add employee</button></td><td><textarea id="schedule_lines-'+count+'-notes" name="schedule_lines-'+count+'-notes"></textarea></td>')
			// insert row
			$(this).parent().parent().before(new_row);
			$("#add_row2").attr("the_line",count);
			$("#schedule_lines-"+count+"-painters-0-employee_id").next().next().click(function(event){newPainter(this,event);});
			$("#schedule_lines-"+count+"-gc").prev().click(function(event){delRow(this,event);});
			$("#schedule_lines-"+count+"-painters-0-employee_id").select2();
			// Activate new painter select
			//$("#schedule_lines-"+line_number+"-painters-"+count+"-employee_id").select2();
		})	
```
As you can see, it can be a huge mess. After coding above, I decided to just make request to server to add new lines, it is like 20 times more simple. In your wtform you can just have add_lines_button = SubmitField ("Add Lines"), and on request.method == "POST" you just check if request.form.get("add_lines_button") == "Add Lines", if it does, then you add lines to the form in the backend and return the same rendered template with updated form.

**Comment by cisko3000** [comment]
Oh look, this is a simple way of doing through javascript:

http://stackoverflow.com/questions/23915132/how-can-i-dynamically-add-a-wtforms-textfield-to-a-fieldlist-using-jquery

This is what I did in the javascript I posted above, but obviously my form was more complex.

**Comment by paris3200** [comment]
I think doing it on the server side is much more elegant.  I will give that a try.  Thanks!

**Pull request merged**
